version: '3'
services:
  backend:
    build: .
    container_name: "faircombine-backend"
    ports:
      - "8000:80"
    depends_on:
      - redis
    volumes:
      - ./app:/faircombine/app

  redis:
    image: redis/redis-stack-server:latest
    command: redis-stack-server --save "60 1"
    container_name: "faircombine-redis"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/var/lib/redis-stack/