version: '3'
services:
  backend:
    build:
      context: .
      target: main
    container_name: "faircombine-backend"
    ports:
      - "8000:80"
    depends_on:
      - redis
    volumes:
      - ./app:/faircombine/app
      - ./session_files:/faircombine/session_files

  redis:
    image: redis/redis-stack-server:latest
    command: redis-stack-server --save "60 1"
    container_name: "faircombine-redis"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/var/lib/redis-stack/

  celery:
    build:
      context: .
      target: celery
    depends_on:
      - backend
    container_name: "faircombine-celery"
    command: celery -A app.celery.celery_app worker -l INFO
    volumes:
      - ./app:/faircombine/app

